### ISSUE TITLE
FYI: pip install on 0.2.1 didn't work

### ISSUE THREAD

**Issue by teuben** [keflavich/image_registration#14]
pip install didn't work (see below), but a clone and traditional source build was ok.

pip install image_registration
Collecting image_registration
  Downloading image_registration-0.2.1.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s701bv59/image-registration/setup.py", line 28, in <module>
        execfile('image_registration/version.py')
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s701bv59/image-registration/

**Comment by keflavich** [comment]
This means the pypi version is out of date.  I've updated it.
