### ISSUE TITLE
pip install 0.2.2 not working yet

### ISSUE THREAD

**Issue by teuben** [keflavich/image_registration#15]
sorry, with the fix, still not working for me.

pip install image_registration
Collecting image_registration
  Downloading image_registration-0.2.2.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 160kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-06e7clhx/image-registration/setup.py", line 8, in <module>
        import ah_bootstrap
    ImportError: No module named 'ah_bootstrap'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-06e7clhx/image-registration/

**Comment by keflavich** [comment]
I've updated astropy-helpers and uploaded another new version.  Try again?

**Comment by teuben** [comment]
I tried it in a clean miniconda2, but it still fails

pip install image_registration
Collecting image_registration
  Downloading image_registration-0.2.3.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 3.0MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BTBFyH/image-registration/setup.py", line 8, in <module>
        import ah_bootstrap
    ImportError: No module named ah_bootstrap
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BTBFyH/image-registration/

**Comment by keflavich** [comment]
OK, thanks.  @bsipocz, do you recognize this error?  Does it mean I set up the package-template wrong?

**Comment by bsipocz** [comment]
@keflavich - my guess would be that you use a very old template. I can have a look, maybe tomorrow the earliest.

**Comment by jakirkham** [comment]
Same issue with 0.2.3.

It looks like the `ah_bootstrap` git submodule included in the repo is not landing in the PyPI package. Though it is still imported in `setup.py`. I'm unclear on whether `ah_bootstrap` should be in the PyPI package or if the `ImportError` should be suppressed.

**Comment by bsipocz** [comment]
@jakirkham - yes, they should have been included in sdist, apparently MANIFEST needs to be updated.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/keflavich/image_registration/pull/17 ), which I think should fix this. Would appreciate feedback on it.
