### ISSUE TITLE
FITS_tools already included

### ISSUE THREAD

**Issue by juliotux** [keflavich/image_registration#23]
Hi @keflavich 

Why FITS_tools is set as dependecy in the code if it is already included as a sub-folder?

Removing it from the dependencies makes possible to simply create anaconda packages with `python setup.py bdist_conda`.

**Comment by juliotux** [comment]
Thanks @keflavich, I'll keep looking to the image_registration and, if it get updated, I'll pack FITS_tools too. I use it for my pipeline and I'm packing everything in my Anaconda cloud.

**Comment by keflavich** [comment]
Sounds good.  If you want to have a go at refactoring the code further, PRs are welcome, I just don't have the time to do work that isn't strictly necessary for functionality right now
