### ISSUE TITLE
upsampling - non-rectangular image

### ISSUE THREAD

**Issue by jtlz2** [keflavich/image_registration#7]
Just to add to #6 - I am now trying to carry out the same operation on a non-rectangular FITS image, but it's giving NaNs everywhere (NaN is the fill value to make a rectangular image).

I can't image this will give something sensible, but I'd like to try anyway in case. So do you know a way to circumvent the NaN issue? Thanks!

**Comment by keflavich** [comment]
Use `np.nan_to_num` to replace the NaNs with zeros before upsampling, then use a threshold to turn all the zeros back to nans, e.g. `im[np.abs(im)<0.0001] = np.nan`.  If you have a lot of data that are very close to zero, you could use `np.nan_to_num` to set the NaNs to a value that does not occur in your data (e.g., -999) in the same way.

**Comment by jtlz2** [comment]
@keflavich Thanks - works!
